name: Deploy
on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run code:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  build-and-push-client-image:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/client/Dockerfile
          push: true
          tags: |
            ghcr.io/zhadko-bazilevych/quotes/client:latest
            ghcr.io/zhadko-bazilevych/quotes/client:${{ github.sha }}

  build-and-push-server-image:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/server/Dockerfile
          push: true
          tags: |
            ghcr.io/zhadko-bazilevych/quotes/server:latest
            ghcr.io/zhadko-bazilevych/quotes/server:${{ github.sha }}

  build-and-push-caddy-image:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push caddy image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/caddy/Dockerfile
          push: true
          tags: |
            ghcr.io/zhadko-bazilevych/quotes/caddy:latest
            ghcr.io/zhadko-bazilevych/quotes/caddy:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build-and-push-client-image
      - build-and-push-server-image
      - build-and-push-caddy-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          {
            echo "GIT_COMMIT_HASH=${GITHUB_SHA}"
            echo "DB_USER=${{ secrets.DB_USER }}"
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
            echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}"
            echo "BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}"
            echo "CLIENT_URL=${{ secrets.CLIENT_URL }}"
          } > stack.env

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: quotes
          file: docker-stack.yaml
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          ssh_key: ${{ secrets.VPS_SSH_KEY }}
          env_file: stack.env
